# Disable specific SwiftLint rules globally
disabled_rules:
  - closure_parameter_name

# Alternatively, you can enable all rules first and disable specific ones
disabled_rules:

# Exclude specific files or directories from linting
excluded:
